"""first migration

Revision ID: 60ec9f22e0ed
Revises: 
Create Date: 2020-01-08 15:52:05.091579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ec9f22e0ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    op.drop_table('products')
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='friends_pkey')
    )
    op.create_table('products',
    sa.Column('product_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.create_table('country',
    sa.Column('countryid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('countryname', sa.VARCHAR(length=45), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
